name: Update Deals

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-deals:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd scraper
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    
    - name: Run scraper
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        cd scraper
        python scraper_env.py
    
    - name: Generate deals.json
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        cd scraper
        python -c "from scraper_env import SavingsGuruScraperEnv; scraper = SavingsGuruScraperEnv(); scraper.generate_deals_json()"
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/deals.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update deals.json - $(date +'%Y-%m-%d %H:%M:%S')" && git push)