name: Update Deals

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  update-deals:
    runs-on: ubuntu-latest
    environment: Production - savingsguru
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        ref: production
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd scraper
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    
    - name: Run scraper
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        cd scraper
        python scraper_env.py
    
    - name: Generate deals.json
      env:
        GOOGLE_SHEETS_CREDS: ${{ secrets.GOOGLE_SHEETS_CREDS }}
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
      run: |
        cd scraper
        python -c "from scraper_env import SavingsGuruScraperEnv; scraper = SavingsGuruScraperEnv(); scraper.generate_deals_json()"
    
    - name: Deploy to Vercel
      if: success()
      run: |
        curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_${{ secrets.VERCEL_PROJECT_ID }}/savingsguru-modern" \
             -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}"